autoVideo/autoVideo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie.urls')),
]

# 以下を定義
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoVideo/movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('wait/<str:key>', views.WaitView.as_view(), name='wait_key'),
    path('movieMake/<str:key>', views.movieMake, name='movieMake_key'),
    path('movieMake/', views.movieMake, name='movieMake'),
    path('play/<str:key>', views.WaitView.as_view(), name='play'),
    path('imageCreate', views.ImageCreateView.as_view(), name='imageCreate'),
    path('newImage/<int:pk>', views.NewImageView.as_view(), name='newImage'),
    # path('newImage', views.NewImageView.as_view(), name='newImage'),
]

autoVideo/movie/models.py
from django.db import models
from datetime import datetime

# Create your models here.
TEXT_TAG_CHOICES = (
    ('SchoolLife', '大学生活'),
    ('Lab', '研究室'),
    ('Shop', '学食'),
)

class Image(models.Model):
    """画像"""
    image = models.ImageField(verbose_name='画像ファイル', upload_to='image/', null=False)
    text_tag = models.CharField(verbose_name='テキストタグ', max_length=50, null=False, choices=TEXT_TAG_CHOICES)
    effect_tag = models.CharField(verbose_name='エフェクトタグ', max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(verbose_name='作成日時', null=False, default=datetime.now())
    updated_at = models.DateTimeField(verbose_name='更新日時', null=False, default=datetime.now())


class Music(models.Model):
    """音楽"""
    music = models.FileField(verbose_name='音楽ファイル', upload_to='music/', null=False)
    created_at = models.DateTimeField(verbose_name='作成日時', null=False, default=datetime.now())
    updated_at = models.DateTimeField(verbose_name='更新日時', null=False, default=datetime.now())


class Movie(models.Model):
    """動画"""
    movie = models.FileField(verbose_name='動画ファイル', upload_to='movie/', null=False)
    created_at = models.DateTimeField(verbose_name='作成日時', null=False, default=datetime.now())
    updated_at = models.DateTimeField(verbose_name='更新日時', null=False, default=datetime.now())


# class Photo(models.Model):
#     # file = models.FileField('ファイル')
#     image = models.ImageField(upload_to='plays')
#     created_at = models.DateTimeField('作成日時', null=False, default=datetime.now())
#     tag_name = models.TextField('タグ名称', null=True)
#     tag_ruby = models.TextField('タグ振り仮名', null=True)

autoVideo/movie/forms.py
from django import forms
from .models import Image
#
# TEXT_TAG_CHOICES = (
#     ('SchoolLife', '大学生活'),
#     ('Lab', '研究室'),
#     ('Shop', '学食'),
# )
#
class ImagesForm(forms.ModelForm):
        # image = forms.ImageField()
    class Meta:
        model = Image
        fields = ('image', 'text_tag')
        # widgets = {
        #     'image': forms.ImageField(
        #         label='画像ファイル',
        #     ),
        #     'message': forms.CharField(
        #         label='テキストタグ',
        #     ),
        # }
        # image = forms.ImageField(
        #     label='画像ファイル',
        # )
        #
        # text_tag = forms.CharField(
        #     label='テキストタグ',
        # )

autoVideo/movie/views.py
from multiprocessing import Process
from django.conf import settings
# from django.shortcuts import redirect
from django.shortcuts import render, redirect
from django.views import generic
from .models import Image
from . import mymodel
import os
from .forms import ImagesForm
from django.urls import reverse
import csv

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = 'movie/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "MyPage"
        return context


# def Wait(self, request, *args, **kwargs):



class WaitView(generic.TemplateView):
    template_name = 'movie/wait.html'

    # def get(key=''):
    #     useimage_record = Image.objects.filter(text_tag=self.kwargs.get('key')).order_by('created_at').reverse()[:10] #上位10件
    # #     for record in useimage_record:
    # #         print(record.Image)
    #     # Image.objects.order_by('created_at').reverse()
    #     return

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["key"] = self.kwargs.get('key')
        useimage_record = Image.objects.filter(text_tag=self.kwargs.get('key')).order_by('created_at')[:10] #上位10件
        # for record in useimage_record:
        #     print(record.image)
        return context


def movieMake(request, key):
    useimage_record = Image.objects.filter(text_tag=key).order_by('created_at')[:10] #上位10件
    image_list = [os.path.join(settings.MEDIA_ROOT, str(record.image)) for record in useimage_record ]
    effect_list = [str(record.effect_tag) for record in useimage_record ]
    os.makedirs(settings.CSV_URL, exist_ok=True)
    with open(settings.CSV_URL+'/tag_data_.csv', 'w') as f_AI:
        w_AI = csv.writer(f_AI, lineterminator='\n')
        for i in range(10):
            w_AI.writerow([image_list[i]] + [effect_list[i]])
        # print(str(image_list[i]) +': ' + str(effect_list[i]))





    #タグ生成
    # mymodel.main(api_key=settings.CLARIFAI_API_KEY, image_list=image_list, outpath=settings.CSV_URL)
    # 動画生成

    return redirect('movie:index')


class PlayView(generic.TemplateView):
    template_name = 'movie/play.html'

# class ImageCreateView(generic.View):
#     template_name = 'movie/imageCreate.html'
#     form_class = ImagesForm
#
#
#     def get(self, request, *args, **kwargs):
#         form = self.form_class()
#         return render(request, self.template_name, {'form': form})
#
#
#     def post(self, request, *args, **kwargs):
#         form = self.form_class(request.POST)
#         print(self)
#         if form.is_valid():
#             return redirect('movie:newImage', kwargs={'image': form.image})
#         return render(request, self.template_name, {'form': form})


class ImageCreateView(generic.CreateView):
    template_name = 'movie/imageCreate.html'
    model = Image
    # form_class = ImagesForm
    fields = ['text_tag', 'image']
    # fields = "__all__"

    def get_success_url(self):
        # print(reverse('movie:newImage', kwargs={'image': self.object.image}))
        # return reverse('movie:newImage', kwargs={'image': self.object.image})
        return reverse('movie:newImage', kwargs={'pk':self.object.pk})
    # success_url = reverse_lazy('base:top')


class NewImageView(generic.TemplateView):
    template_name = 'movie/newimage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        record = Image.objects.get(pk=self.kwargs.get('pk'))
        context["image"] = record.image
        context["text_tag"] = record.text_tag
        os.makedirs(settings.CSV_URL, exist_ok=True)
        #タグ生成
        image = os.path.join(settings.MEDIA_ROOT, str(record.image))
        effect_tag = mymodel.oneEffect(api_key=settings.CLARIFAI_API_KEY, image=image)
        # 動画生成oneEffect(api_key, image):
        record.effect_tag = effect_tag
        record.save() # レコード更新
        context["effect_tag"] = effect_tag

        return context

# class WaitKeyView(generic.TemplateView):
#     template_name = 'movie/wait.html'

    # def main(self):
    #     return HttpResponse("Hello, world.")

autoVideo/movie/templates/movie/imageCreate.html
<form method="post" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit">
</form>

<button type="button" onClick="location.href='{% url 'movie:index' %}';" >
  ホームに戻る
</button>

autoVideo/movie/templates/movie/index.html
{% load static %}
<!DOCTYPE html>
<header>
  <link rel="stylesheet" type="text/css" href="{% static 'movie/index.css' %}">
</header>

<body>
  <h1>ムービーメーカー</h1>

  <h2>タグ選択</h2>

  <button class="btn-sticky button1" type="button" onClick="location.href='{% url 'movie:wait_key' 'SchoolLife'  %}';" value="大学生活">
    大学生活
  </button>

  <button class="btn-sticky button1" type="button" onClick="location.href='{% url 'movie:wait_key' 'Lab' %}';" value="研究室">
    研究室
  </button>

  <button class="btn-sticky button2" type="button" onClick="location.href='{% url 'movie:wait_key' 'Shop' %}';" value="学食">
    大学周辺
  </button>

  <a href=imageCreate>新しい画像</a>

</body>

autoVideo/movie/templates/movie/memo.html
{% load static %}
<!DOCTYPE html>
<header>
  <link rel="stylesheet" type="text/css" href="{% static 'movie/index.css' %}">
</header>

<body>
  <h1>ムービーメーカー</h1>

  <a href="{% url 'movie:wait' %}">test</a>

  <h2>タグ選択</h2>
  <form method="get">
    <button class="button " type="button" onClick="location.href='{% url 'movie:wait' %}';" value="学食">
      学食
    </button>
  </form>
  <form method="get">
    <button class="button " name="buttonB" onClick="location.href='{% url 'movie:wait' %}';" value="大学">
      大学
    </button>
  </form>
</body>

autoVideo/movie/templates/movie/newimage.html
{% load static %}
<!DOCTYPE html>

<header>

</header>

<body>
<h1>アップロードされました</h1>
<h2>付与されたエフェクトタグ: {{ effect_tag }}</h2>
<h3>アップロード画像</h3>
<img src="{{ image.url }}" />
<h3>テキストタグ: {{ text_tag }}</h3>
</body>

<button type="button" onClick="location.href='{% url 'movie:imageCreate' %}';" >
  アップロードを続ける
</button>

<button type="button" onClick="location.href='{% url 'movie:index' %}';" >
  ホームに戻る
</button>

autoVideo/movie/templates/movie/play.html
{% load static %}
<!DOCTYPE html>

autoVideo/movie/templates/movie/wait.html
{% load static %}
<!DOCTYPE html>

<header>
  <meta http-equiv="refresh" content=" 0.1; url={% url 'movie:movieMake_key' key%}">
</header>

<body>
<h1>ムービーメーカー</h1>
<h2>Wait</h2>
{{ key }}
</body>